/* Generated By:JJTree: Do not edit this line. /Users/pellier/Developpement/PDDL4J/src/pddl4j/lexer/LexerTreeConstants.java */

package pddl4j.lexer;

public interface LexerTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTDOMAIN = 2;
  public int JJTREQUIRE_DEF = 3;
  public int JJTREQUIRE_KEY = 4;
  public int JJTTYPE_DEF = 5;
  public int JJTTYPED_LIST = 6;
  public int JJTTYPE = 7;
  public int JJTPRIMITIVE_TYPE = 8;
  public int JJTCONSTANT_DEF = 9;
  public int JJTCONSTANT = 10;
  public int JJTPREDICATE_DEF = 11;
  public int JJTATOMIC_FORMULA_SKELETON = 12;
  public int JJTPREDICATE = 13;
  public int JJTVARIABLE = 14;
  public int JJTFUNCTION_DEF = 15;
  public int JJTATOMIC_FUNCTION_SKELETON = 16;
  public int JJTFUNCTOR = 17;
  public int JJTFUNCTION_TYPED_LIST = 18;
  public int JJTFUNCTION_TYPE = 19;
  public int JJTCON_GD = 20;
  public int JJTAND_CON_GD = 21;
  public int JJTFORALL_CON_GD = 22;
  public int JJTAT_END_CON_GD = 23;
  public int JJTALWAYS_CON_GD = 24;
  public int JJTSOMETIME_CON_GD = 25;
  public int JJTWITHIN_CON_GD = 26;
  public int JJTAT_MOST_ONCE_CON_GD = 27;
  public int JJTSOMETIME_AFTER_CON_GD = 28;
  public int JJTSOMETIME_BEFORE_CON_GD = 29;
  public int JJTALWAYS_WITHIN_CON_GD = 30;
  public int JJTHOLD_DURING_CON_GD = 31;
  public int JJTHOLD_AFTER_CON_GD = 32;
  public int JJTGD = 33;
  public int JJTAND_GD = 34;
  public int JJTOR_GD = 35;
  public int JJTNOT_GD = 36;
  public int JJTIMPLY_GD = 37;
  public int JJTEXISTS_GD = 38;
  public int JJTFORALL_GD = 39;
  public int JJTATOMIC_FORMULA = 40;
  public int JJTTERM = 41;
  public int JJTLITERAL = 42;
  public int JJTNOT_ATOMIC_FORMULA = 43;
  public int JJTF_COMP = 44;
  public int JJTBINARY_COMP = 45;
  public int JJTGREATER_COMP = 46;
  public int JJTGREATER_EQUAL_COMP = 47;
  public int JJTLESS_EQUAL_COMP = 48;
  public int JJTLESS_COMP = 49;
  public int JJTEQUAL_COMP = 50;
  public int JJTF_EXP = 51;
  public int JJTNUMBER = 52;
  public int JJTOP = 53;
  public int JJTBINARY_OPERATION = 54;
  public int JJTADD_OP = 55;
  public int JJTSUBSTRACT_OP = 56;
  public int JJTMULTIPLY_OP = 57;
  public int JJTDIVIDE_OP = 58;
  public int JJTUNARY_OP = 59;
  public int JJTF_HEAD = 60;
  public int JJTSTRUCTURE_DEF = 61;
  public int JJTACTION_DEF = 62;
  public int JJTACTION_NAME = 63;
  public int JJTACTION_DEF_BODY = 64;
  public int JJTPRE_GD = 65;
  public int JJTEMPTY_OR = 66;
  public int JJTAND_PRE_GD = 67;
  public int JJTFORALL_PRE_GD = 68;
  public int JJTPREF_GD = 69;
  public int JJTNAMED_PREF_GD = 70;
  public int JJTPREF_NAME = 71;
  public int JJTEFFECT = 72;
  public int JJTAND_C_EFFECT = 73;
  public int JJTC_EFFECT = 74;
  public int JJTFORALL_EFFECT = 75;
  public int JJTWHEN_CON_EFFECT = 76;
  public int JJTCOND_EFFECT = 77;
  public int JJTAND_P_EFFECT = 78;
  public int JJTP_EFFECT = 79;
  public int JJTASSIGN_OP = 80;
  public int JJTASSIGN = 81;
  public int JJTSCALE_UP = 82;
  public int JJTSCALE_DOWN = 83;
  public int JJTINCREASE = 84;
  public int JJTDECREASE = 85;
  public int JJTDURATION_ACTION_DEF = 86;
  public int JJTDA_SYMBOL = 87;
  public int JJTDA_DEF_BODY = 88;
  public int JJTDURATION_CONSTRAINT = 89;
  public int JJTAND_SIMPLE_DURATION_CONSTRAINT = 90;
  public int JJTSIMPLE_DURATION_CONSTRAINT = 91;
  public int JJTAT_SIMPLE_DURATION_CONSTRAINT = 92;
  public int JJTAT_START_SIMPLE_DURATION_CONSTRAINT = 93;
  public int JJTAT_END_SIMPLE_DURATION_CONSTRAINT = 94;
  public int JJTD_OP = 95;
  public int JJTEQUAL_D_OP = 96;
  public int JJTGEQUAL_D_OP = 97;
  public int JJTLEQUAL_D_OP = 98;
  public int JJTVAR_DURATION = 99;
  public int JJTD_VALUE = 100;
  public int JJTDA_GD = 101;
  public int JJTFORALL_DA_GD = 102;
  public int JJTAND_DA_GD = 103;
  public int JJTPREF_TIMED_GD = 104;
  public int JJTNAMED_PREF_TIMED_GD = 105;
  public int JJTTIMED_GD = 106;
  public int JJTOVER_TIMED_GD = 107;
  public int JJTOVER_ALL_TIMED_GD = 108;
  public int JJTAT_TIMED_GD = 109;
  public int JJTAT_START_TIMED_GD = 110;
  public int JJTAT_END_TIMED_GD = 111;
  public int JJTINTERVAL = 112;
  public int JJTDA_EFFECT = 113;
  public int JJTDA_ASSIGN_OP = 114;
  public int JJTDA_ASSIGN = 115;
  public int JJTDA_SCALE_UP = 116;
  public int JJTDA_SCALE_DOWN = 117;
  public int JJTDA_INCREASE = 118;
  public int JJTDA_DECREASE = 119;
  public int JJTWHEN_DA_EFFECT = 120;
  public int JJTFORALL_DA_EFFECT = 121;
  public int JJTAND_DA_EFFECT = 122;
  public int JJTTIMED_EFFECT = 123;
  public int JJTAT_F_ASSIGN_DA_EFFECT = 124;
  public int JJTAT_START_F_ASSIGN_DA_EFFECT = 125;
  public int JJTAT_END_F_ASSIGN_DA_EFFECT = 126;
  public int JJTAT_DA_EFFECT = 127;
  public int JJTAT_START_DA_EFFECT = 128;
  public int JJTAT_END_DA_EFFECT = 129;
  public int JJTASSIGN_OP_T = 130;
  public int JJTINCREASE_ASSIGN_OP_T = 131;
  public int JJTDECREASE_ASSIGN_OP_T = 132;
  public int JJTF_EXP_T = 133;
  public int JJTCONTINOUS_VARIABLE = 134;
  public int JJTF_ASSIGN_DA = 135;
  public int JJTF_EXP_DA = 136;
  public int JJTDA_BINARY_OP = 137;
  public int JJTDA_ADD_OP = 138;
  public int JJTDA_SUBSTRACT_OP = 139;
  public int JJTDA_MULTIPLY_OP = 140;
  public int JJTDA_DIVIDE_OP = 141;
  public int JJTDA_UNARY_OP = 142;
  public int JJTDERIVED_DEF = 143;
  public int JJTPROBLEM = 144;
  public int JJTPROBLEM_NAME = 145;
  public int JJTDOMAIN_NAME = 146;
  public int JJTOBJECT_DECLARATION = 147;
  public int JJTINIT = 148;
  public int JJTINIT_EL = 149;
  public int JJTEQUAL_INIT_EL = 150;
  public int JJTTIMED_LITERAL = 151;
  public int JJTGOAL = 152;
  public int JJTCONSTRAINTS = 153;
  public int JJTPREF_CON_GD = 154;
  public int JJTAND_PREF_CON_GD = 155;
  public int JJTNAMED_PREF_CON_GD = 156;
  public int JJTFORALL_PREF_CON_GD = 157;
  public int JJTMETRIC_SPEC = 158;
  public int JJTMAXIMIZE = 159;
  public int JJTMINIMIZE = 160;
  public int JJTMETRIC_F_EXP = 161;
  public int JJTVIOLATED_PREF_EXP = 162;
  public int JJTCONSTANT_F_HEAD = 163;
  public int JJTTOTAL_TIME = 164;
  public int JJTBINARY_OP_METRIC_F_EXP = 165;
  public int JJTADD_OP_METRIC_F_EXP = 166;
  public int JJTSUBSTRACT_OP_METRIC_F_EXP = 167;
  public int JJTMULTI_OP_METRIC_F_EXP = 168;
  public int JJTMULTIPLY_NARITY_OP_METRIC_F_EXP = 169;
  public int JJTADD_NARITY_OP_METRIC_F_EXP = 170;
  public int JJTUNARY_OP_METRIC_F_EXP = 171;


  public String[] jjtNodeName = {
    "ROOT",
    "void",
    "DOMAIN",
    "REQUIRE_DEF",
    "REQUIRE_KEY",
    "TYPE_DEF",
    "TYPED_LIST",
    "TYPE",
    "PRIMITIVE_TYPE",
    "CONSTANT_DEF",
    "CONSTANT",
    "PREDICATE_DEF",
    "ATOMIC_FORMULA_SKELETON",
    "PREDICATE",
    "VARIABLE",
    "FUNCTION_DEF",
    "ATOMIC_FUNCTION_SKELETON",
    "FUNCTOR",
    "FUNCTION_TYPED_LIST",
    "FUNCTION_TYPE",
    "CON_GD",
    "AND_CON_GD",
    "FORALL_CON_GD",
    "AT_END_CON_GD",
    "ALWAYS_CON_GD",
    "SOMETIME_CON_GD",
    "WITHIN_CON_GD",
    "AT_MOST_ONCE_CON_GD",
    "SOMETIME_AFTER_CON_GD",
    "SOMETIME_BEFORE_CON_GD",
    "ALWAYS_WITHIN_CON_GD",
    "HOLD_DURING_CON_GD",
    "HOLD_AFTER_CON_GD",
    "GD",
    "AND_GD",
    "OR_GD",
    "NOT_GD",
    "IMPLY_GD",
    "EXISTS_GD",
    "FORALL_GD",
    "ATOMIC_FORMULA",
    "TERM",
    "LITERAL",
    "NOT_ATOMIC_FORMULA",
    "F_COMP",
    "BINARY_COMP",
    "GREATER_COMP",
    "GREATER_EQUAL_COMP",
    "LESS_EQUAL_COMP",
    "LESS_COMP",
    "EQUAL_COMP",
    "F_EXP",
    "NUMBER",
    "OP",
    "BINARY_OPERATION",
    "ADD_OP",
    "SUBSTRACT_OP",
    "MULTIPLY_OP",
    "DIVIDE_OP",
    "UNARY_OP",
    "F_HEAD",
    "STRUCTURE_DEF",
    "ACTION_DEF",
    "ACTION_NAME",
    "ACTION_DEF_BODY",
    "PRE_GD",
    "EMPTY_OR",
    "AND_PRE_GD",
    "FORALL_PRE_GD",
    "PREF_GD",
    "NAMED_PREF_GD",
    "PREF_NAME",
    "EFFECT",
    "AND_C_EFFECT",
    "C_EFFECT",
    "FORALL_EFFECT",
    "WHEN_CON_EFFECT",
    "COND_EFFECT",
    "AND_P_EFFECT",
    "P_EFFECT",
    "ASSIGN_OP",
    "ASSIGN",
    "SCALE_UP",
    "SCALE_DOWN",
    "INCREASE",
    "DECREASE",
    "DURATION_ACTION_DEF",
    "DA_SYMBOL",
    "DA_DEF_BODY",
    "DURATION_CONSTRAINT",
    "AND_SIMPLE_DURATION_CONSTRAINT",
    "SIMPLE_DURATION_CONSTRAINT",
    "AT_SIMPLE_DURATION_CONSTRAINT",
    "AT_START_SIMPLE_DURATION_CONSTRAINT",
    "AT_END_SIMPLE_DURATION_CONSTRAINT",
    "D_OP",
    "EQUAL_D_OP",
    "GEQUAL_D_OP",
    "LEQUAL_D_OP",
    "VAR_DURATION",
    "D_VALUE",
    "DA_GD",
    "FORALL_DA_GD",
    "AND_DA_GD",
    "PREF_TIMED_GD",
    "NAMED_PREF_TIMED_GD",
    "TIMED_GD",
    "OVER_TIMED_GD",
    "OVER_ALL_TIMED_GD",
    "AT_TIMED_GD",
    "AT_START_TIMED_GD",
    "AT_END_TIMED_GD",
    "INTERVAL",
    "DA_EFFECT",
    "DA_ASSIGN_OP",
    "DA_ASSIGN",
    "DA_SCALE_UP",
    "DA_SCALE_DOWN",
    "DA_INCREASE",
    "DA_DECREASE",
    "WHEN_DA_EFFECT",
    "FORALL_DA_EFFECT",
    "AND_DA_EFFECT",
    "TIMED_EFFECT",
    "AT_F_ASSIGN_DA_EFFECT",
    "AT_START_F_ASSIGN_DA_EFFECT",
    "AT_END_F_ASSIGN_DA_EFFECT",
    "AT_DA_EFFECT",
    "AT_START_DA_EFFECT",
    "AT_END_DA_EFFECT",
    "ASSIGN_OP_T",
    "INCREASE_ASSIGN_OP_T",
    "DECREASE_ASSIGN_OP_T",
    "F_EXP_T",
    "CONTINOUS_VARIABLE",
    "F_ASSIGN_DA",
    "F_EXP_DA",
    "DA_BINARY_OP",
    "DA_ADD_OP",
    "DA_SUBSTRACT_OP",
    "DA_MULTIPLY_OP",
    "DA_DIVIDE_OP",
    "DA_UNARY_OP",
    "DERIVED_DEF",
    "PROBLEM",
    "PROBLEM_NAME",
    "DOMAIN_NAME",
    "OBJECT_DECLARATION",
    "INIT",
    "INIT_EL",
    "EQUAL_INIT_EL",
    "TIMED_LITERAL",
    "GOAL",
    "CONSTRAINTS",
    "PREF_CON_GD",
    "AND_PREF_CON_GD",
    "NAMED_PREF_CON_GD",
    "FORALL_PREF_CON_GD",
    "METRIC_SPEC",
    "MAXIMIZE",
    "MINIMIZE",
    "METRIC_F_EXP",
    "VIOLATED_PREF_EXP",
    "CONSTANT_F_HEAD",
    "TOTAL_TIME",
    "BINARY_OP_METRIC_F_EXP",
    "ADD_OP_METRIC_F_EXP",
    "SUBSTRACT_OP_METRIC_F_EXP",
    "MULTI_OP_METRIC_F_EXP",
    "MULTIPLY_NARITY_OP_METRIC_F_EXP",
    "ADD_NARITY_OP_METRIC_F_EXP",
    "UNARY_OP_METRIC_F_EXP",
  };
}
